#define BLOCK_SIZE 0x1000000
#include "mutation_detailed.pb.h"
#include <climits>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <google/protobuf/generated_message_util.h>
#include <ios>
#include <mutex>
#include <string>
#include <sys/mman.h>
#include <tbb/flow_graph.h>
#include <tbb/task_group.h>
#include <utility>
#define LOAD
#include "google/protobuf/io/coded_stream.h"
#include "mutation_annotated_tree.hpp"
#include <fcntl.h>
#include <fstream>
#include <zlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <vector>
