name: usher
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - cxx-compiler
  - cmake=3.20
  - protobuf=3.12.4 
  - make
  - autoconf
  - boost-cpp
  - mafft
  - git
  - wget
  - rsync
  - openmpi=3.1.0
  - openssh
  - isa-l
  - libhwloc
